import fs from 'node:fs';
const path = 'src/App.jsx';
let content = fs.readFileSync(path, 'utf8');
content = content.replace('Affan Ahmad', 'Ahmed Khan');
content = content.replace('22 â€¢ Full Stack Software &amp; Infrastructure Engineer â€¢ MLOps / LLMOps', '3rd-year CS student • Backend &amp; Full-Stack Developer • 6+ client apps shipped');
content = content.replace('href="https://docs.google.com/document/d/1Adyb0O_W_E6B_YIdW5IV3jPi3K4Iz53cR8Q6bT-1Xcs/edit?usp=sharing" target="_blank" rel="noreferrer" className="rounded-lg p-2 transition-all duration-200 hover:-translate-y-0.5 hover:scale-110 hover:bg-muted" aria-label="Resume">\n                  <IconDoc className="h-5 w-5 text-foreground" />', 'href="mailto:ahmedkhanofficials@gmail.com" target="_blank" rel="noreferrer" className="rounded-lg p-2 transition-all duration-200 hover:-translate-y-0.5 hover:scale-110 hover:bg-muted" aria-label="Email">\n                  <IconMail className="h-5 w-5 text-foreground" />');
content = content.replace('© 2026 Affan Ahmad', '© 2026 Ahmed Khan');
content = content.replace(/<span className="text-foreground">CS Senior at FAST NUCES<\/span> and <span className="text-foreground">Software Engineer at Motive<\/span>, building solutions that help fleets operate in a more <span className="text-foreground">compliant, safe, productive, and profitable way\.<\/span>\s*<\/p>\s*<p className="mb-4">\s*Actively exploring <span className="text-foreground">cloud systems, MLOps, and LLMOps<\/span>, learning how modern software and machine learning models are designed, deployed, monitored, and scaled\.<\/p>\s*<p>Outside the terminal, youâ€™ll usually find me gaming or diving into documentaries\.<\/p>/s, `<span className="text-foreground">Backend &amp; Full-Stack Developer</span> at Air University Islamabad, focused on building scalable, secure, and high-performance products.</p>\n              <p className="mb-4">I’ve shipped production applications across ecommerce, AI, SaaS, and realtime systems — with hands-on work in <span className="text-foreground">Node.js, React, Next.js, MongoDB, Redis, Stripe, and OpenAI</span>.</p>\n              <p>Outside the terminal, you’ll usually find me improving systems, iterating on client work, or exploring product ideas that feel useful in the real world.</p>`);
fs.writeFileSync(path, content);
